node {
    stage ('Build') {
        sh ' echo "building project...." '
    }

    stage ('Test') {
        sh ' echo "Testing the project...." '
    }

    stage ('Deploy') {
        sh ' echo "Deploying the project" '
    }
}