node {
    stage ('Build') {
        sh 'echo "building project....'
    }

    stage ('Test') {
        sh 'echo "testing tests....'
    }

    stage ('Deploy') {
        sh 'echo "Deploying the project.... "'
    }
}