pipeline {
    agent any

    environment {
        DOCKER_CREDS = credentials('docker')
        TAG = "v${env.BUILD_NUMBER}"
        IMAGE = "${DOCKER_CREDS_USR}/maven-jenkins-demo:${TAG}"
    }

    stages {

        stage('Checkout the code') {
            steps {
                echo 'Checking out....'
                checkout scm

                sh 'pwd'
                sh 'ls -la'
            }
        }

        stage('Maven Clean') {
            steps {
                dir('java-maven') {
                    sh 'mvn clean'
                }
            }
        }

        stage('Maven Build and Compile') {
            steps {
                dir('java-maven') {
                    sh 'mvn compile'
                }
            }
        }

        stage('Maven Test') {
            steps {
                dir('java-maven') {
                    sh 'mvn test'
                }
            }

            post {
                always {
                    script {
                        if (fileExists('java-maven/target/surefire-reports')) {
                            echo "Publishing JUnit test results..."
                            junit 'java-maven/target/surefire-reports/*.xml'
                        } else {
                            echo "No JUnit test report directory found — skipping test report publishing."
                        }
                    }
                }
            }
        }

        stage('Package') {
            steps {
                dir('java-maven') {
                    echo "Packaging application into JAR..."
                    sh 'mvn package -DskipTests'
                }
            }

            post {
                success {
                    archiveArtifacts artifacts: 'java-maven/target/*.jar',
                                     fingerprint: true
                }
            }
        }

        stage('Static Code Analysis') {
            steps {
                echo "Running code analysis (Simulated)..."
                sh 'echo "Code quality check passed"'
            }
        }

        stage('Docker Build and Tag') {
            steps {
                dir('java-maven') {
                    echo "Building Docker image..."
                    sh 'docker build -t maven:latest .'
                    sh 'docker tag maven:latest ${IMAGE}'
                }
            }
        }

        stage('Docker Push') {
            steps {
                echo "Logging in to Docker..."

                sh '''
                    echo "$DOCKER_CREDS_PSW" | docker login \
                    -u "$DOCKER_CREDS_USR" \
                    --password-stdin
                '''

                sh 'docker push ${IMAGE}'
            }
        }
        
           stage('Docker run') {
            steps {
                echo "run in to Docker..."

                sh 'docker run -d --name maven-demo-${BUILD_NUMBER} ${IMAGE}'
            }
        }

    }

    post {
        success {
            echo "Build ${env.BUILD_NUMBER} completed"
        }

        failure {
            echo "Build ${env.BUILD_NUMBER} failed"
        }

        always {
            cleanWs()
        }
    }
}