pipeline {
    agent any
    stages {
        stage('Build')
           steps{
             echo "building...."
           }

           steps {
              echo "Testing...."
           }

            steps {
              echo "deploying"
           }
    }
}