pipeline {
    agent any
    stages {
        stage('Build') {     
           steps {
             sh ' echo "building...." '
           }
        }
        stage('Test'){
         steps {
            sh ' echo "Testting...." '
         }
        }
        
        stage('Deploy'){
         steps{
          sh ' echo "Deploying...." '
         }
        }
         
    }
}