pipeline {
    agent any
    
    environment {
         DOCKER_CREDS = credentials('docker')
         TAG = "v${env.BUILD_NUMBER}"
         IMAGE = "${DOCKER_CREDS_USR}/python-proj:${TAG}"
    }

    stages {
        stage('checkout the code') {
            steps {
                git branch: 'main', url: 'https://github.com/devops-harsh/jenkins.git'
            }
        }
        
        stage('lint') {
            steps {
               catchError(buildResult: 'SUCCESS', stageResult: 'UNSTABLE') {
                          dir('python-portfolio-app') {
                  sh "pip3 install flake8 --break-system-packages "
                   sh 'flake8 app.py '
                  }
             }
        }
           }
         
        
        stage('docker build and tag') {
            steps {
                dir('python-portfolio-app') {
                sh '''
                 docker login -u ${DOCKER_CREDS_USR} -p ${DOCKER_CREDS_PSW}
                 docker build -t python-proj:${TAG} .
                 docker tag python-proj:${TAG} ${DOCKER_CREDS_USR}/python-proj:${TAG}
                '''
                }
            }
        }
        
        stage('docker push') {
            steps {
                sh ' docker push ${DOCKER_CREDS_USR}/python-proj:${TAG}'
            }
        }
        
        stage('docker run') {
            steps {
                sh ' docker run --name python-${TAG} -d -p 5002:5000 ${IMAGE}'
            }
        }
        
        
    }

    post {
            success {
                echo "Build success"
            }
            failure {
                echo "Build failed at $BUILD_NUMBER"
            }
        }  
}
