pipeline {
    agent any
    
    environment {
         DOCKER_CREDS = credentials('docker')
         IMAGE = "${DOCKER_CREDS_USR}/python-proj:v1"
    }

    stages {
        stage('checkout the code') {
            steps {
                git branch: 'main', url: 'https://github.com/devops-harsh/jenkins.git'
            }
        }
        
        stage('lint') {
            steps {
                dir('python-portfolio-app') {
                //   sh "pip3 install flake8 --break-system-packages "
                   sh 'flake8 app.py '
                  }
             }
        }
        
        stage('docker build and tag') {
            steps {
                dir('python-portfolio-app') {
                sh '''
                 docker login -u ${DOCKER_CREDS_USR} -p ${DOCKER_CREDS_PSW}
                 docker build -t python-proj:v1 .
                 docker tag python-proj:v1 ${DOCKER_CREDS_USR}/python-proj:v1
                '''
                }
            }
        }
        
        stage('docker push') {
            steps {
                sh ' docker push ${DOCKER_CREDS_USR}/python-proj:v1'
            }
        }
        
        stage('docker run') {
            steps {
                sh ' docker run --name python -d -p 5002:5000 ${IMAGE}'
            }
        }
        
        
    }

    post {
            success {
                echo "Build success"
            }
            failure {
                echo "Build failed at $BUILD_NUMBER"
            }
        }  
}
